gear

diff --git a/jopla b/jopla
--- a/jopla
+++ b/jopla
@@ -1,10 +1,13 @@
 #!/bin/bash
 
 SELF=$(basename $0)
-DB=~/.config/joplin/database.sqlite
 
+# tools
 SQLC="sqlite3"
+DIA="whiptail"
 
+# defaults
+DB=~/.config/joplin/database.sqlite
 GUI=1
 ACTION="list_folders"
 
@@ -50,7 +53,7 @@ list_folders(){
         # a bit of redirect black magic here to workaround pipe subshells
 
         calc_size
-        FLD=$(whiptail --clear --notags --title "Jopla" --menu "Folders" ${H} ${W} ${MH}\
+        FLD=$(${DIA} --clear --notags --title "Jopla" --menu "Folders" ${H} ${W} ${MH}\
             ${MNU[@]} \
             3>&1 1>&2 2>&3)
         echo "${FLD}"
@@ -58,7 +61,9 @@ list_folders(){
 }
 
 # mandatory checks
-command -v "$SQLC" >/dev/null 2>&1 || err "$SQLC not found, aborting"
+for gear in $SQLC $DIA; do
+    command -v "$gear" >/dev/null 2>&1 || err "$gear not found, aborting"
+done
 
 # getopts
 while getopts ":d:fh" opt; do
